### ISSUE TITLE
Reddit & Discord deep integration

### ISSUE THREAD

**Issue by nullpixel** [dynasticdevelop/place#224]
As many of our users know, our discord server is quite central to operations on place - factions use it to communicate, and we use it to hear back from our community. 

We already utilise and provide OAuth, and could expand this integration.

As far as discord goes, I'm proposing we:

1. **Give donors a role & channel** on Discord.
2. **Allow users to link their Place 2.0 name and Discord name**, so that the discord name appears by the place name, and so the discord channel nickname can be set to the place username

**Will propose an update a rewritten faction system.**

~~Place 2.0 originates from Reddit's /r/place, so we also have pretty big roots in reddit too. Most place users are part of "factions" which are typically members of subreddits or discord servers. Factions are an integral part of Place 2.0, and we do not do much to accommodate them. Therefore, I propose we~~ 

~~1. **Allow users to link subreddits / discord servers to their place account** in order to show people what faction they belong to.~~

~~Obviously, this would have some limitations, with number of factions a user can "join" being one of them.~~
~~There also needs to be some form of validation that the said user is actually in the faction, which is where this proposal falls short.~~

---

To make the faction system a reality, we need your input, from you, the user. Comment letting us know how you think factions should work!

---

**TODO:**

Any help in achieving these goals would be happily received! Join [our discord](https://discord.gg/gZMZ6Xq) and let us know what you're planning on working on <3

- [ ] Reimplement OAuth integration, allowing users to add OAuth accounts to existing place accounts
- [ ] Create some form of module that integrates with discord and adds a role every time the donors field is changed?
- [ ] Discuss how factions should be implemented & implement them.

**Comment by deadbaed** [comment]
wen eta bios plz thx

**Comment by Alex1331xela** [comment]
For factions, I think the best way to implement it would be to have one person (who knows the Place 2.0 community well) act as a sort of 'Faction Manager'. They would have the ability to change each Place 2.0 user's linked faction discord/subreddit, and they would be in charge of verifying that users are indeed a part of their stated faction. Also if a user was to join/leave a certain faction, the user could go to the 'Faction Manager' to get their linked faction discord/subreddit changed.

**Comment by AppleBetas** [comment]
Honestly I think the ideal implementation of this would just be our own independent action system, where users can create factions on the site, and get access to some extra features like it displaying on their profile and a badge in the chat/pixel info, maybe setting a faction home, and a private faction chat for them. Discords and such could be linked afterwards, but any implementation based solely on those is flawed in my opinion.

**Comment by nullpixel** [comment]
agreed.
